### ISSUE TITLE
How can I load/create KV from .yml in a consul container during startup?

### ISSUE THREAD

**Issue by aniskhan001** [hashicorp/docker-consul#101]
I have this `config.yml`:

```
app:
    port: 5002
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 30
    redis_ttl: 100800

redis:
    host: localhost
    port: 6379
    db: 0
    prefix: choice

database:
    host: localhost
    port: 3306
    name: choice
    username: root
    password: 12345
```

And this is my `docker-compose.yml`:

```
version: '3.3'

services: 
  web:
    restart: always
    image: choice
    environment: 
      - CHOICE_CONSUL_URL=consul:8500
      - CHOICE_CONSUL_PATH=choice
    ports: 
      - 5555:5555
    links:
      - mysql
      - redis
  
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=choice
    ports: 
      - 3306:3306
  
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
  
  consul:
    image: consul:latest
    ports: 
      - 8500:8500
```

I could initialize this config using a curl request after the container is up:
`curl --request PUT --data-binary @config.yml http://localhost:8500/v1/kv/choice`

But how can I tell the `consul` container to initialize KV from this file during startup?

**Comment by winrey** [comment]
The same question.
Any solutions? QAQ

**Comment by nafania217518** [comment]
Any updates?

**Comment by RamBoddapati** [comment]
Help  me here. am too  having same issue

**Comment by RamBoddapati** [comment]
thanks for response. I am still not clear on this. what is that other containers in same n/w? is that another  same consul container in same n/w? plz clarify me.

**Comment by aferen** [comment]
I couldn't find any solution supported by docker official consul image. I prepared a bash script and added it to the _docker-entrypoint.sh_ file in the container by using `sed` command in Dockerfile so that it is called when the container starts up. Script runs `curl` request to consul every 5 seconds and if consul leader's ip returns, consul has started and key/values are created with `consul kv put`.

`Dockerfile`
```Dockerfile
FROM consul

USER root
COPY ./config /consul/config
RUN chmod +x /consul/config/init.sh
RUN sed -ie 's|^\(set .*\)|\1\nsh /consul/config/init.sh \&|' /usr/local/bin/docker-entrypoint.sh
```
`init.sh`
```bash
#!/bin/bash
while ! curl -f -s http://$CONSUL_HTTP_ADDR/v1/status/leader | grep "[0-9]:[0-9]"; do
  sleep 5
done
consul kv put choice @/consul/config/config.yml
# consul kv put <key> @<file-path>
```
`server.json`
```json
{
  "node_name": "consul-server",
  "server": true,
  "ui": true,
  "data_dir": "/consul/data",
  "addresses": {
    "http" : "0.0.0.0"
  }
}
```
`docker-compose.yml`
```yaml
version: '3.6'
services:
  consul:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"
    volumes:
      - consul-volume:/consul/data
    ports:
      - "8500:8500"
    command: "agent -server --bootstrap -data-dir=/consul/data"

volumes:
  consul-volume:
```
The folder structure should look like as below. You can start consul with `docker-compose up -d --build` and see your config.yml file as value under key named choice. 
```
.
├── config
│   ├── config.yml
│   ├── init.sh
│   └── server.json
├── docker-compose.yml
└── Dockerfile
```
**Note:** The bash script runs every time the container starts, so the key is overwritten each time with `consul kv put`. You can use `consul kv get <key> >/dev/null || consul kv put <key> @<file-path>` instead of `consul kv put <key> @<file-path>` if you want to run only if the key is not exist.

You can also refer to [link](https://stackoverflow.com/a/65570653) which I used while preparing the solution.
