### ISSUE TITLE
Ability to run as nonroot user

### ISSUE THREAD

**Issue by johnypony3** [hashicorp/docker-consul#103]
#### Overview of the Issue

We are using consul on a kubernetes cluster. We have a [pod security policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) that requires the pod to run under as a nonroot user. When the application is stood up, the logs contain the following error: `chown: /consul/config: Operation not permitted`. This is because `chown` is not available to the nonroot user account.

#### Reproduction Steps

1. Standup consul in kubernetes with a nonroot security context as below
```yaml
#pod
securityContext:
  fsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

#container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  runAsUser: 10001
```

1. View logs, notice error:  `chown: /consul/config: Operation not permitted`

### Operating system and Environment details

Kubernetes, Consul container

### Log Fragments

chown: /consul/config: Operation not permitted
