### ISSUE TITLE
How to set management token without run consul acl bootstrap?

### ISSUE THREAD

**Issue by 4n70w4** [hashicorp/docker-consul#176]
Hi! I can't google info about set up my own management token  for ACL.

I would like to set this token through environment variables or something else.

**Comment by dvoltaire** [comment]
Add this to your acl entry:
--
acl {
  enabled                  = true
  default_policy           = "deny"
  enable_token_persistence = true
  tokens {
    initial_management = "your-token-value-in-base64"
  }
}

**Comment by blake** [comment]
> I would like to set this token through environment variables or something else.

You can use the `CONSUL_LOCAL_CONFIG` environment variable to pass this configuration into the container. Here's an example of using this with Docker compose.

```yaml
# docker-compose.yml
---
version: "3.8"
services:
  consul:
    image: hashicorp/consul:1.11.4
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "acl": {
            "enabled": true,
            "default_policy": "deny",
            "enable_token_persistence": true,
            "tokens": {
              "initial_management": "UUID of the initial management token",
            }
          }
        }
```
