### ISSUE TITLE
The `consul` user does not have write access to /consul/data in the offical docker image.

### ISSUE THREAD

**Issue by barbarello** [hashicorp/docker-consul#20]
# https://github.com/hashicorp/consul/issues/2025

@jhmartin 
the z or Z options do not work for me

Ubuntu 16.04 , no SELinux,

$ docker version
Client:
Version: 1.11.2
API version: 1.23
Go version: go1.5.4
Git commit: b9f10c9
Built: Wed Jun 1 22:00:43 2016
OS/Arch: linux/amd64

Server:
Version: 1.11.2
API version: 1.23
Go version: go1.5.4
Git commit: b9f10c9
Built: Wed Jun 1 22:00:43 2016
OS/Arch: linux/amd64

docker logs:

$ docker logs consul
WARNING: ca_cert.pem does not contain exactly one certificate or CRL: skipping
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
WARNING: ca-cert-consulca.pem does not contain exactly one certificate or CRL: skipping
==> WARNING: Expect Mode enabled, expecting 3 servers
==> Starting Consul agent...
==> Error starting agent: Failed to configure keyring: mkdir /data/serf: permission denied

**Comment by deviantony** [comment]
Also having this issue, Consul container is started this way: 

```
$ docker run -d --restart always --net host -v "/opt/consul:/consul/data" -p 8500:8500 --name consul_node1 consul agent -client <NODEIP> -bind <NODEIP> -server -bootstrap-expect 3

==> Error starting agent: Failed to start Consul server: Failed to start Raft: mkdir /consul/data/raft: permission denied
```

**Comment by ryansch** [comment]
@slackpad We could chown that location in the entrypoint to enable bind mounts from the host like the above example.

**Comment by slackpad** [comment]
Hi @ryansch that's an interesting idea. Which example are you referring to?

**Comment by etki** [comment]
I can't use image because of this issue as well.
I'm not sure if chown will help because most people will mount directory in host system, and that would require root permissions to access; i'm not sure Docker is capable of doing that mapping current days.
Is there any need in using other user than root in container?

**Comment by fletch22** [comment]
I have a workaround. If I chown the shared volume on the host with the consul Id and group ID, it then works.

sudo chown -R 100:1000 /var/consul-data-stuff

This works by giving ownership to the the consul user (id=100) and group (gid=1000) that will be running in the container. 

Chowning it before docker run fixed it for me.

**Comment by oryband** [comment]
ping! let's get this fixed.

**Comment by oryband** [comment]
@fletch22 100:1000 is not always the user/group id assigned to consul.

**Comment by fletch22** [comment]
@oryband Agree. Ids might vary. Substitute your own. Not a solution. Just a workaround.

**Comment by bkleef** [comment]
Please do not use the hardcoded path here: https://github.com/hashicorp/docker-consul/blob/47e4cde898e8c51ff62c83cb4c779f2b42841868/0.X/docker-entrypoint.sh#L80 but the one specified in `-data-dir`.

**Comment by anton-pydev** [comment]
I am experiencing same issue with official docker image 0.7.2 and 0.7.5 again 
I am running on kubernetes cluster 1.5.2 with persistant volumes .
Getting an error : ==> Error starting agent: Failed to configure keyring: mkdir /var/lib/consul/serf: permission denied

**Comment by brianqcgames** [comment]
Has anyone figured this out? I am seeing the same issue with Kubernetes and  consul:0.8.1.

My volume is an EBS volume.

Thanks!

**Comment by kaskavalci** [comment]
@slackpad we still experience this issue with latest image, as with some others in this thread. Can you please recommend a workaround?

**Comment by kladiv** [comment]
+1
I suggest to not hardcoded path /consul/... but use the environment variable e.g.
```
CONSUL_DATA_DIR=${CONSUL_DATA_DIR:=/consul/data}
CONSUL_CONFIG_DIR=${CONSUL_CONFIG_DIR:=/consul/config}
...
if [ "$(stat -c %u /consul/data)" != "$(id -u consul)" ]; then
        chown consul:consul ${CONSUL_DATA_DIR}
    fi
    if [ "$(stat -c %u /consul/config)" != "$(id -u consul)" ]; then
        chown consul:consul ${CONSUL_CONFIG_DIR}
    fi
```

**Comment by barryib** [comment]
@kladiv @shane-containership I think that chown should be done recursively on all configuration file already present in those directories.

**Comment by HelLViS69** [comment]
Same error on Consul 1.1.0 using a docker volume

**Comment by HelLViS69** [comment]
Same error on Consul 1.1.0 using a docker volume

**Comment by Murf** [comment]
same error using vfile shared volume

**Comment by mkeeler** [comment]
@Murf @HelLViS69 Are you trying to use a data dir other than /consul/data and still having permissions issues.

**Comment by HelLViS69** [comment]
@mkeeler Yep, I tried that and still having problems. The fix in my case was to modify the docker-entrypoint.sh, replacing this part:

`chown consul:consul /consul`

with this one:

`chown -R consul:consul /consul`

**Comment by mariusgrigoriu** [comment]
chown in an entrypoint is not friendly for k8s clusters with restrictive pod security policies. What coudl we do to run without root, without chown, and as an arbitrary, high UID?

**Comment by cirix** [comment]
Hi is this issue addressed if we don't want to run the containers with elevated user privileges? My preference would be to run a consul cluster inside a k8 farm.
kr
Nik

**Comment by nthienan** [comment]
Still experience this issue with `consul:1.4.4`. I run consul on Openshift with hostPath pv.
```yaml
     securityContext:
        privileged: true
        fsGroup: 1000
      containers:
      - name: consul
        image: consul:1.4.4
        volumeMounts:
        - name: data
          mountPath: /consul/data
        - name: config
          mountPath: /etc/consul/config
      volumes:
      - name: config
        configMap:
          name: consul
      serviceAccount: consul
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: manual
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      selector:
        matchLabels:
          type: local
          app: consul
          component: server
```
