### ISSUE TITLE
How to write docker-compose setup?

### ISSUE THREAD

**Issue by askaribragimov** [hashicorp/docker-consul#45]
It is a slight disappointing that docker-compose setup is completely nonexistent in the current official image. 

Could you please provide information about how to specify the following docker-compose image:
- client mode
- in a cluster (when cluster is not in Docker)

**Comment by ronyrun** [comment]
```
version: '2'
services:
  c1:
    image: consul:0.7.2
    command: consul agent -dev -ui
    container_name: cs1
    ports:
        - "8500:8500"
  c2:
    image: consul:0.7.2
    command: consul agent -dev -join=cmain
    container_name: cs2
    links:
      - c1:cmain
  c3:
    image: consul:0.7.2
    command: consul agent -dev -join=cmain
    container_name: cs3
    links:
      - c1:cmain
```
