### ISSUE TITLE
`k8s` update breaks consul deployment

### ISSUE THREAD

**Issue by aisengard** [hashicorp/docker-consul#85]
The new security update `1.7.14`, `1.8.9`, and `1.9.4` makes `configMap`s readonly by default: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.7.md#other-notable-changes

> Changes secret, configMap, downwardAPI and projected volumes to mount read-only, instead of allowing applications to write data and then reverting it automatically. Until version 1.11, setting the feature gate ReadOnlyAPIDataVolumes=false will preserve the old behavior. (#58720, @joelsmith)

This breaks a deployment that uses a configMap to define the `consul` config file. From `consul` logs: 

```
chown: /consul/config: Read-only file system
```

Why does `consul` need to `chown` the config file?

**Comment by aisengard** [comment]
To those having the same issue, we solved this by passing in the configMap value as the environment variable `CONSUL_LOCAL_CONFIG` like so:

```
env:
  - name: CONSUL_LOCAL_CONFIG
    valueFrom:
      configMapKeyRef:
        name: consul-config
        key: server.json
```

**Comment by IvanovOleg** [comment]
@aisengard , I am getting `==> config: Open failed on /consul/config/server.json. open /consul/config/server.json: no such file or directory` if I don't mount a configmap

**Comment by aisengard** [comment]
If you set the environment variable, you can remove the `-config-file` argument.

**Comment by innovia** [comment]
still getting the same issue
```/usr/local/bin/docker-entrypoint.sh: line 51: can't create /consul/config/local.json: Read-only file system```

**Comment by innovia** [comment]
to whoever struggle understanding this:

since 1.8.9 the option to readwrite from configmap is disabled unless you configure the kubelet like so
```
kubelet:
    featureGates:
      ReadOnlyAPIDataVolumes: "true"
```

this is not going to work if you already in a failed state.

now for the fix:

you need to remove the config map volume mount and the server flag from the yaml

```yaml
 # - "-config-file=/consul/config/server.json"`
volumeMounts:
            - name: data
              mountPath: /consul/data
            # - name: config
            #   mountPath: /consul/config
```
now add the env var like so:
```yaml
 - name: CONSUL_LOCAL_CONFIG
              value: '{
                "ca_file": "/etc/tls/ca.pem",
                "cert_file": "/etc/tls/consul.pem",
                "key_file": "/etc/tls/consul-key.pem",
                "verify_incoming": true,
                "verify_outgoing": true,
                "verify_server_hostname": true,
                "ports": {
                  "https": 8443
                }
              }'
```

this instructs consul to get its config from an env var instead of a file where the docker image will attempt to chown the config for the console user.
