### ISSUE TITLE
docker-compose dns_search option does not propogate

### ISSUE THREAD

**Issue by m1stermanager** [hashicorp/docker-consul#88]
when writing a docker-compose such as the following:
```
version "3"

services:
  consul:
    image: consul:latest
    dns_search: "somewhere.example.com"
```

the service consul does not have an entry in `/etc/resolv.conf` for `search somewhere.example.com`

this is working on other images so I'm not sure if i'm just too much of a consul newbie or what.

i can give any additional info. thank you very much!
